# Site settings
title: West Michigan R User Group
email: WestMichiganRUserGroup@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  This group gets together monthly to discuss R programming,
  statistical techniques using R, finding help with R, R packages, and more.
  We meet up every second Tuesday of the month at 6pm.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "WestMichiganRUserGroup.github.io" # the base hostname & protocol for your site
paginate: 5
github_username:  WestMichiganRUserGroup

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-paginate

